# Generated by Django 3.2.9 on 2021-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerChk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_age', models.IntegerField(default=0)),
                ('c_type', models.CharField(default='', max_length=15)),
                ('c_cycle', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ChildChk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_type', models.CharField(default='', max_length=15)),
                ('ch_month', models.IntegerField(default=0)),
                ('ch_item', models.CharField(default='', max_length=50)),
                ('ch_method', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DisaCtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=15)),
                ('d_location', models.CharField(default='', max_length=50)),
                ('d_latitude', models.FloatField(default=0.0)),
                ('d_longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DisaFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(default='', max_length=15)),
                ('d_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NormalChk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_age', models.IntegerField(default=0)),
                ('n_chkitem', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PragCtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=15)),
                ('p_location', models.CharField(default='', max_length=50)),
                ('p_latitude', models.FloatField(default=0.0)),
                ('p_longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PragFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_month', models.IntegerField(default=0)),
                ('p_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(default='9', primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('chkprag', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('chkarmy', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('chkdisa', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
    ]
